"use strict";
exports.__esModule = true;
var express = require('express');
var app = express();
var port = process.env.PORT || 4000;
var path = require('path');
app.use(express.json());
app.use(express.static(path.join(__dirname, 'client', 'build')));
var userRoute_1 = require("./routes/userRoute");
app.use('/user', userRoute_1["default"]);
app.listen(port, function () { console.log('Server listen on port', port); });
